<a href="https://colab.research.google.com/github/Pinalli/Bootcamp_MachineLearning/blob/master/Trabalho_pr%C3%A1tico_M%C3%B3dulo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabalho Prático 3

## Enunciado
1. Baixar os arquivos referentes as bases de dados e acessá-las pelo collab.
2. Obter informações sobre números de features e instâncias dos datasets.
3. Identificar a existência de dados faltantes nos datasets.
4. Separar os conjuntos de treino e teste, usando a função train_test_slipt, com
test_size = 0.25 e random_state = 42.
5. Importar o sklearn para:
6. Aplicar à base diabetes_numeric.csv o modelo de regressão linear.
7. Avaliar as métricas R2, MAE e MSE.
8. Aplicar à base bloodtransf.csv o modelo SVC, com kernel=rbf.
9. Avaliar as métricas Acurácia, Precision, Recall, F1 e AUROC
10. Aplicar à base wine.csv o modelo kmeans.
11. Identificar o número de clusters mais adequado de acordo com o dataset
12. Avaliar as métricas Coeficiente de Silhueta, Davies-Bouldin Score e Mutual
Information.


In [ ]:
import pandas as pd
import numpy as np

## Perguntas
1: Sobre o número de atributos da base de regressão, marque a alternativa CORRETA:  
a) A base tem (43,3) atributos.  
b) A base tem 3 atributos.  
c) A base tem 43 + 3 = 46 atributos.  
d) A base tem 43 atributos.  

In [ ]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/victoraccete/ML-bootcamp/master/Mod_3/datasets/diabetes_numeric.csv')
diabetes.shape

(43, 3)

In [ ]:
print("R: {}".format(diabetes.shape[1]))

R: 3


2: Sobre o número de instâncias da base de classificação, marque a alternativa CORRETA:  
a) A base tem (748,5) instâncias.  
b) A base tem 748 instâncias.  
c) A base tem 753 instâncias.  
d) A base tem 5 instâncias.

In [ ]:
blood_transf = pd.read_csv('https://raw.githubusercontent.com/victoraccete/ML-bootcamp/master/Mod_3/datasets/bloodtransf.csv')
blood_transf.shape

(748, 5)

In [ ]:
print("R: {}".format(blood_transf.shape[0]))

R: 748


3: Sobre a base de clusterização, marque a alternativa CORRETA:  
a) A base tem 178 instâncias divididas em 4 classes.  
b) A base tem 4 atributos e 3 instâncias.  
c) A base tem 178 atributos e 4 instâncias.  
d) A base tem 178 instâncias divididas em 3 classes.

In [ ]:
wine = pd.read_csv('https://raw.githubusercontent.com/victoraccete/ML-bootcamp/master/Mod_3/datasets/wine.csv')
wine.shape

(178, 14)

In [ ]:
# now we want to check the numbers of classes
wine['class'].nunique()

3

R: 178 instâncias divididas em 3 classes. 

4: Sobre dados faltantes, marque a alternativa CORRETA:  
a) Apenas as bases wine.csv e bloodtransf.csv têm dados faltantes.  
b) Todas as bases têm dados faltantes.  
c) Nenhuma base tem dados faltantes.  
d) Apenas a base wine.csv tem dados faltantes.

In [ ]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        43 non-null     float64
 1   deficit    43 non-null     float64
 2   c_peptide  43 non-null     float64
dtypes: float64(3)
memory usage: 1.1 KB


In [ ]:
blood_transf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      748 non-null    int64
 1   V2      748 non-null    int64
 2   V3      748 non-null    int64
 3   V4      748 non-null    int64
 4   Class   748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [ ]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   class                           178 non-null    int64  
 1   Alcohol                         178 non-null    float64
 2   Malic_acid                      178 non-null    float64
 3   Ash                             178 non-null    float64
 4   Alcalinity_of_ash               178 non-null    float64
 5   Magnesium                       178 non-null    int64  
 6   Total_phenols                   178 non-null    float64
 7   Flavanoids                      178 non-null    float64
 8   Nonflavanoid_phenols            178 non-null    float64
 9   Proanthocyanins                 178 non-null    float64
 10  Color_intensity                 178 non-null    float64
 11  Hue                             178 non-null    float64
 12  OD280%2FOD315_of_diluted_wines  178 

R: Nenhuma base tem dados faltantes.

5: Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica r2:  
a) O r2 encontrado é aproximadamente 0.76.  
b) O r2 encontrado é aproximadamente 0.22.  
c) O r2 encontrado é aproximadamente 0.47.  
d) O r2 encontrado é aproximadamente 0.65.

In [ ]:
print(diabetes.columns)
input = diabetes.drop('c_peptide', axis=1).values # .values returns a numpy array
print(type(input))
print(input[:5])

Index(['age', 'deficit', 'c_peptide'], dtype='object')
<class 'numpy.ndarray'>
[[  5.2  -8.1]
 [  8.8 -16.1]
 [ 10.5  -0.9]
 [ 10.6  -7.8]
 [ 10.4 -29. ]]


In [ ]:
labels = diabetes.c_peptide.values
print(type(labels))
print(labels[:5])

<class 'numpy.ndarray'>
[4.8 4.1 5.2 5.5 5. ]


In [ ]:
# splitting the dataset
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(input, labels, test_size=0.25, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(32, 2)
(11, 2)
(32,)
(11,)


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics  

lin_regression = LinearRegression().fit(X_train, y_train)
regression_preds = lin_regression.predict(X_test)
print('R2: {0:.2f}'.format(metrics.r2_score(y_test, regression_preds))) 

R2: 0.22


6: Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica MAE:  
a) O MAE encontrado é aproximadamente 0.61.  
b) O MAE encontrado é aproximadamente 0.51.  
c) O MAE encontrado é aproximadamente 0.81.  
d) O MAE encontrado é aproximadamente 0.71.

In [ ]:
print('MAE: {0:.2f}'.format(metrics.mean_absolute_error(y_test, regression_preds))) 

MAE: 0.61


7: Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica MSE:  
a) O MSE encontrado é aproximadamente 0.47.  
b) O MSE encontrado é aproximadamente 0.53.  
c) O MSE encontrado é aproximadamente 0.22.  
d) O MSE encontrado é aproximadamente 0.61.

In [ ]:
print('MSE: {0:.2f}'.format(metrics.mean_squared_error(y_test, regression_preds))) 

MSE: 0.47


8: Em relação a modelagem utilizando o SVM, marque a alternativa CORRETA sobre a métrica acurácia:  
a) A acurácia encontrada é aproximadamente 0.75.  
b) A acurácia encontrada é aproximadamente 0.60.  
c) A acurácia encontrada é aproximadamente 0.70.  
d) A acurácia encontrada é aproximadamente 0.65.

In [ ]:
print(blood_transf.columns)
input = blood_transf.drop(columns=['Class']).values # another way different from the used previously
print(type(input))
print(input[:5])
labels = blood_transf.iloc[:, 4].values
print(type(labels))
print(labels[:5])

Index(['V1', 'V2', 'V3', 'V4', 'Class'], dtype='object')
<class 'numpy.ndarray'>
[[    2    50 12500    98]
 [    0    13  3250    28]
 [    1    16  4000    35]
 [    2    20  5000    45]
 [    1    24  6000    77]]
<class 'numpy.ndarray'>
[2 2 2 2 1]


In [ ]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(input, labels, test_size=0.25, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(561, 4)
(187, 4)
(561,)
(187,)


In [ ]:
from sklearn.svm import SVC

svm_clf = SVC(kernel='rbf')
svm_clf.fit(X_train, y_train)

svm_preds = svm_clf.predict(X_test)
print("Acc: {0:.2f}".format(metrics.accuracy_score(y_test, svm_preds)))

Acc: 0.75


9: Em relação a modelagem utilizando o SVM, marque a alternativa CORRETA sobre as métricas precision e recall:  
a) Os valores de precision e recall encontrados são aproximadamente 1.0 e 0.02, respectivamente.  
b) Os valores de precision e recall encontrados são aproximadamente 0.02 e 0.98, respectivamente.  
c) Os valores de precision e recall encontrados são aproximadamente 0.02 e 1, respectivamente.  
d) Os valores de precision e recall encontrados são aproximadamente 0.08 e 0.88, respectivamente.

In [ ]:
print(metrics.classification_report(y_test, svm_preds))

              precision    recall  f1-score   support

           1       0.75      1.00      0.86       139
           2       1.00      0.02      0.04        48

    accuracy                           0.75       187
   macro avg       0.87      0.51      0.45       187
weighted avg       0.81      0.75      0.65       187



R: 1.0 e 0.02, respectivamente

10: Em relação a modelagem utilizando o SVM, marque a alternativa CORRETA sobre a métrica f1:  
a) A f1 encontrada é aproximadamente 0.12.  
b) A f1 encontrada é aproximadamente 0.16.  
c) A f1 encontrada é aproximadamente 0.04.  
d) A f1 encontrada é aproximadamente 0.08.

R: 0.04

11: Em relação a modelagem utilizando o SVM, marque a alternativa CORRETA sobre a métrica AUROC:  
a) A AUROC encontrada é aproximadamente 0.51, indicando que esse modelo resolve adequadamente o problema  
b) A AUROC encontrada é aproximadamente 0.51, indicando que o modelo apresenta um resultado próximo de uma baseline aleatório.  
c) A AUROC encontrada é aproximadamente 0.70, indicando que esse modelo resolve adequadamente o problema.  
d) A AUROC encontrada é aproximadamente 0.70, indicando que esse modelo não resolve adequadamente o problema.

In [ ]:
print("R: {0:.2f}, muito próximo de um baseline aleatório".format(metrics.roc_auc_score(y_test, svm_preds)))

R: 0.51, muito próximo de um baseline aleatório


12: Em relação a modelagem utilizando o Kmeans, marque a alternativa CORRETA sobre o número de clusters:  
a) O número de clusters mais adequado para o problema é 3.  
b) O número de clusters mais adequado para o problema é 4.  
c) O número de clusters mais adequado para o problema é 2.  
d) O número de clusters mais adequado para o problema é 7.

R: 3

13: Em relação a modelagem utilizando o Kmeans, marque a alternativa CORRETA sobre a métrica Coeficiente de Silhueta:  
a) O coeficiente de silhueta encontrado é aproximadamente 0.55.  
b) O coeficiente de silhueta encontrado é aproximadamente 0.60.  
c) O coeficiente de silhueta encontrado é aproximadamente 0.50.  
d) O coeficiente de silhueta encontrado é aproximadamente 0.58.

In [ ]:
input = wine.drop('class', axis=1).values # could also be done with wine.iloc[:, 1:]
labels = wine.iloc[:, 0].values

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(input, labels, test_size=0.25, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(133, 13)
(45, 13)
(133,)
(45,)


In [ ]:
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters=3, random_state=42)
clustering.fit(X_train)

cluster_preds = clustering.predict(X_test)

In [ ]:
from sklearn.metrics import cluster

print("R: {0:.2f}".format(metrics.silhouette_score(X_test, cluster_preds)))

R: 0.55


14: Em relação a modelagem utilizando o Kmeans, marque a alternativa CORRETA sobre a métrica Davies-Bouldin Score:  
a) O Davies-Bouldin Score encontrado é aproximadamente 0.59.  
b) O Davies-Bouldin Score encontrado é aproximadamente 0.50.  
c) O Davies-Bouldin Score encontrado é aproximadamente 0.54.  
d) O Davies-Bouldin Score encontrado é aproximadamente 0.57.

In [ ]:
print("R: {0:.2f}".format(metrics.davies_bouldin_score(X_test, cluster_preds)))

R: 0.54


15: Em relação a modelagem utilizando o Kmeans, marque a alternativa CORRETA sobre a métrica Mutual information:  
a) O Mutual information encontrado é aproximadamente 0.53.  
b) O Mutual information encontrado é aproximadamente 0.58.  
c) O Mutual information encontrado é aproximadamente 0.50.  
d) O Mutual information encontrado é aproximadamente 0.55.

In [ ]:
cluster_preds

array([2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 2, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1,
       2, 2, 1, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2,
       1], dtype=int32)

In [ ]:
print("R: {0:.2f}".format(metrics.mutual_info_score(y_test, cluster_preds)))

R: 0.53
